service: fivefingers

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    ROOMS_TABLENAME: ${self:custom.roomsTable}
    CONNECTIONS_TABLENAME: ${self:custom.connectionsTable}
    CORS_ORIGIN: ${self:custom.corsOrigin}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource:
        - Fn::GetAtt: [ RoomsTable, Arn ]
        - Fn::GetAtt: [ ConnectionsTable, Arn ]
        - Fn::Join:
          - ''
          - - Fn::GetAtt: [ ConnectionsTable, Arn ]
            - '/index/roomid-index'

custom:
  corsOrigin: ${opt:corsOrigin, 'http://localhost:3000'}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  roomsTable: ${self:service.name}-rooms-${self:provider.stage}
  connectionsTable: ${self:service.name}-connections-${self:provider.stage}

functions:
  newRoom:
    handler: ApiHandler.newRoom
    events:
      - http:
          method: post
          path: api/rooms/new
          cors:
            origin: ${self:custom.corsOrigin}
  getRoom:
    handler: ApiHandler.getRoom
    events:
      - http:
          method: get
          path: api/rooms
          cors:
            origin: ${self:custom.corsOrigin}
  onConnect:
    handler: SocketHandler.onConnect
    events:
      - websocket:
          route: $connect
  onDisonnect:
    handler: SocketHandler.onDisconnect
    events:
      - websocket:
          route: $disconnect
  onMessage:
    handler: SocketHandler.onMessage
    events:
      - websocket:
          route: $default

resources:
  Resources:
    RoomsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.roomsTable}
        AttributeDefinitions:
          - AttributeName: RoomId
            AttributeType: S
        KeySchema:
          - AttributeName: RoomId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: True
    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.connectionsTable}
        AttributeDefinitions:
          - AttributeName: ConnectionId
            AttributeType: S
          - AttributeName: RoomId
            AttributeType: S
        KeySchema:
          - AttributeName: ConnectionId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: roomid-index
            KeySchema:
              - AttributeName: RoomId
                KeyType: HASH
              - AttributeName: ConnectionId
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: True